---
abstract: 'Password storage implementation based on KDE Wallet.'
author:
  - 'Marcin Kasperski <Marcin.Kasperski@mekk.waw.pl>'
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0.19
  Test::More: 0
  Test::Pod::Coverage: 1.000008
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Passwd-Keyring-KDEWallet
provides:
  Passwd::Keyring::KDEWallet:
    file: lib/Passwd/Keyring/KDEWallet.pm
    version: 0.20
requires:
  Net::DBus: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
